#! /bin/bash
#
# This script installs things.

# Find installers and run them iteratively.
find . -name install | while read installer ; do sh -c "${installer}" ; done

# Install Vim Plug.
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Copy neovim setting.
mkdir -p ~/.config/nvim/
cp ./macOS/.config/nvim/init.vim ~/.config/nvim/
