cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'neovim/neovim'

cask 'java'

brew 'yarn'
brew 'maven'
brew 'gradle'
brew 'vagrant-completion'
brew 'carthage'
brew 'rclone'
brew 'percona-toolkit'
brew 'neovim'
brew 'gnu-sed', args: ["with-default-names"]

# JetBrains
cask 'intellij-idea'
cask 'webstorm'
cask 'pycharm'

# Database Client
cask 'dbeaver-enterprise'

# Other Developer Tools
cask 'sourcetree'
cask 'docker'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vagrant'
cask 'vagrant-manager'
cask 'tunnelblick'
cask 'visual-studio-code'

# Utilities
cask 'shiftit'
cask 'appcleaner'

# Cloud Drive
cask 'amazon-drive'
cask 'rclone-browser'

# Graphic Design
cask 'gimp'
cask 'zeplin'

# Office
cask 'adobe-acrobat-reader'
