cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'neovim/neovim'

cask 'java'

brew 'yarn'
brew 'maven'
brew 'gradle'
brew 'vagrant-completion'
brew 'carthage'
brew 'rclone'
brew 'percona-toolkit'
brew 'neovim'
brew 'gnu-sed', args: ["with-default-names"]

# JetBrains
cask 'intellij-idea'
cask 'webstorm'
cask 'pycharm'

# Database Client
cask 'dbeaver-enterprise'

cask 'sourcetree'
cask 'docker'
cask 'appcleaner'
cask 'shiftit'
cask 'adobe-acrobat-reader'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vagrant'
cask 'vagrant-manager'
cask 'zeplin'
cask 'rclone-browser'
cask 'tunnelblick'
cask 'visual-studio-code'
